### PR TITLE
simplify .travis.yml

### PR DESCRIPTION
**Pull request by stephengroat**
move packages into apt addon
sudo is now required
use node_js build environment
git lfs is now installed by default (https://docs.travis-ci.com/user/customizing-the-build#linux)

### CODE REVIEW

**Comment by lauthieb** [comment]
Hello, thanks a lot but it doesn't work :(

**Comment by stephengroat** [comment]
@lauthieb sorry, i've tried to get the build to work locally, etc but with no luck.

is it possible that there's something in the cache that's causing this issue? could you try clearing the travis cache and rebuilding to see if the issue appears on `master`?

**Comment by stephengroat** [comment]
@lauthieb sorry about that, didn't see that you weren't running `yarn test`

removed that and everything seems to work now. want me to squash the commits?

**Comment by lauthieb** [comment]
Thanks a lot @stephengroat for your contribution. I really appreciate that!
No need to squash, I will do that with `Squash and merge`. Thanks :)

**Pull request merged**
