### PR TITLE
Unroll PR93 and restore master

### PR DESCRIPTION
**Pull request by kodaman2**
Given that @jack-chapman  did not respond to any message I have undone PR93 after trying to cherry pick packages I just couldn't figure out which specific package broke it, probably an issue with webpack or maybe one of the css plugins not sure though.

I branched off 29d3a74485d4baac43744a4c7fd93fb53881a442

Below is a list of additions to this PR:
- PR #95
- style: margin between cards 13100dff63f59dbe901049bbc64cce3f4268b0bd
- PR #107
- Added a few rules to the contributions.md so this doesn't happen again.
- Upped version to 1.2.4 if is all good then downloadl link still need to be updated.

I've tested dev and build on windows 10 and osx mojave, but please have another member test to make sure I didn't miss anything.

@flashadvocate please do the do and ensure GHE still works.

Once this is tested and merged on master, please ensure any new PR's have master merged to their PR otherwise it will undue what I have done and have conflicts for sure.

### CODE REVIEW

**Comment by lauthieb** [comment]
Thank you @kodaman2 for this work.
I’ve just tested on MacOS Mojave and it works too.
I cannot test github enterprise unfortunately...

**Comment by lauthieb** [comment]
You have some conflicts with master branch, did you see that?

**Comment by kodaman2** [comment]
@lauthieb Yes, it is expected since we're using an old branch. You'll have to merge manually in the cmd line and when fixing the conflicts you'll need to select this branch as the correct code not the master code.

If I do a merge master on this branch it will mess it, since master is screwed up.

**Comment by lauthieb** [comment]
Hi @kodaman2, sorry but I don't unterstand what to do. For me it works when I'm on your branch. Do you want that I force push on `master` branch?

**Comment by kodaman2** [comment]
Yes, that can do the job too.

**Comment by lauthieb** [comment]
Do we forget some commits if I force push your branch on master ?

**Comment by kodaman2** [comment]
> Do we lost some commits if I force push your branch on master ?

PR #93 is the only major commit removed.

Have a look at [commits](https://github.com/lauthieb/code-notes/commits/master) and checkout the commits after PR #93 there isn't anything major, and that's why I did this branch manually if it was tons of commits I wouldn't have done it this quick, it would have taken weeks.

**Comment by lauthieb** [comment]
No problem @kodaman2, thanks a lot for this great job. I will force push your Pull Request on master and make a release :)
Thanks.

**Pull request merged**
