### PR TITLE
move node_js version to nvmrc

### PR DESCRIPTION
**Pull request by stephengroat**
removes node js travis dependency
improves compatability with node version managers

### CODE REVIEW

**Comment by lauthieb** [comment]
Thanks @stephengroat for this. We are investigating this bug #110 so nothing can be merged before its correction but after I will merge your proposition ;)

**Comment by lauthieb** [comment]
Can you please fix conflicts and update your branch with just your modifications?
Sorry for the inconvenience it was mandatory to force push `master` after several tries to fix this important bug #110 

Here you can download the new version 1.2.3 : https://github.com/lauthieb/code-notes/releases/tag/1.2.3

Thanks a lot in advance for this.

**Comment by stephengroat** [comment]
@lauthieb fixed

**Comment by lauthieb** [comment]
Thanks @stephengroat

**Comment by lauthieb** [comment]
@stephengroat sorry but the CI is broken with your suggestion.

**Comment by stephengroat** [comment]
@lauthieb could you try a rerun on travis?

all this PR does is move the `nvm install` step from a hard-coded value to a value pulled from the `.nvmrc` file (compare failure here https://travis-ci.org/lauthieb/code-notes/jobs/622698139#L87 and success on master https://travis-ci.org/lauthieb/code-notes/jobs/622661291#L73)

since that's the only difference, i don't think this should have any effect

**Comment by lauthieb** [comment]
Okay for me & Travis CI!
Thanks @stephengroat :)

**Pull request merged**
