### PR TITLE
Fixes #91: Frequently used file types

### LINKED ISSUE #91: Feature request: "Frequently used file types"
**Is your feature request related to a problem? Please describe.**
I can tell I'm going to want to use the same programming languages pretty consistently. It would be nice if I were presented with frequently/recently used ones.

**Describe the solution you'd like**
Next to the dropdown, there could be a couple clickable options.

**Describe alternatives you've considered**
Alternatively, having a typeahead instead of a dropdown could make this less necessary (though still might be useseful)

**Additional context**

Screen Shot 2019-10-01 at 4 48 27 PM

### PR DESCRIPTION
**Pull request by kartik-budhiraja**
Fixes #91 
- Added a searchable dropdown for language type
- The language list is sorted by use frequency
- Top 3 used languages show up as buttons right next to the dropdown

Screen Shot 2019-11-24 at 11 47 43 PM

### CODE REVIEW

**Comment by lauthieb** [comment]
WOW! Thanks a lot @kartik-budhiraja for this wonderful Pull Request! For me it's OK ❤️

**Comment by lauthieb** [comment]
What do you think @benhalpern? It's a pretty cool answer about your issue #91

**Comment by lauthieb** [comment]
@kodaman2 @jack-chapman @bainternet @guastallaigor @stephengroat feel free to add your comments/suggestions/review before I merge this :)

**Comment by kodaman2** [comment]
I don't think anything should be merged until master is fixed.

**Comment by kartik-budhiraja** [comment]
@lauthieb @kodaman2 Let me know if I can help anyways to land this code. :)

**Comment by kodaman2** [comment]
There's an ongoing issue in the latest release (master branch) that imo needs to be addressed before any more PRs get merged. #110 if you are interested in reading more about it, basically at some point during the year a commit broke the app. It looks like just the production, as I couldn't duplicate with dev so something tells me is the minified code perhaps but I haven't been able to fix even after reverting the version on some packages.

**Comment by lauthieb** [comment]
@kartik-budhiraja Can you please fix conflicts and update your branch with just your modifications?
Sorry for the inconvenience it was mandatory to force push master after several tries to fix this important bug #110

Here you can download the new version 1.2.3 : https://github.com/lauthieb/code-notes/releases/tag/1.2.3

Thanks a lot in advance for this.

**Comment by kartik-budhiraja** [comment]
@lauthieb I fixed the branch, so it should be good to go from my side!

**Pull request merged**
