### PR TITLE
Upgrading to vue-cli 4 and electron 8

### PR DESCRIPTION
**Pull request by mszkb**
According to: #94 

**What I have done:**
Complete revamp of folder structure

- upgrading vue-cli 4
- use vue-cli-plugin-electron-builder for project scaffolding
- upgrading to electron 8
- upgrading to spectron 10
- use jest instead of karma, mocha and chai
- moving configurations into vue.config.js
- upgrading to prettier 2

We do not need following files/directories anymore, because they are managed by vue-cli-plugin-electron-builder:
- .electron-vue build files
- Karma tests
- seperate renderer and main folders in src

I left the code as it was before. There is a new version to prettier and I applied the codestyling.

### CODE REVIEW

**Comment by mszkb** [comment]
Sadly it is pretty hard to check what I have done to the sourcecode itself because I moved everything according to vue-cli 4 into the src/ folder instead splitting up into main and renderer.

**Comment by lauthieb** [comment]
Thank you very much @mszkb. I will check this in the following days.

**Comment by lauthieb** [comment]
@mszkb sorry I don't have time for now :'(
I will check that max on Saturday. Thanks a lot.

**Comment by lauthieb** [comment]
Wow amazing work.
All scripts works well. Thanks again @mszkb!

**Comment by lauthieb** [comment]
@mszkb there's a problem...
When I did `npm run build:mac` and installed with the new 1.2.4 dmg file, I've lost all my notes. Fortunately, when I reinstall the 1.2.3 version my notes come back.
Can you please check this problem?
I will let your commit on master but don't make a release until this work again.
Thanks!

**Comment by mszkb** [comment]
I try to replicate and fix this problem on my machine over the weekend :)

**Comment by lauthieb** [comment]
Thanks a lot.

**Pull request merged**
