### PR TITLE
Uninstall-configuration for Windows

### PR DESCRIPTION
**Pull request by kodaman2**
This takes care of the data left behind on windows as per issue #124 

There shouldn't be any data left behind on mac/linux as dmg/appimage are self-contained applications and deleting them should do the trick.

Data will not delete on a new install, only when clicking the `Uninstall Code Notes.exe`  which is the desired end goal.

### CODE REVIEW

**Comment by lauthieb** [comment]
Thanks @kodaman2.
So, when I uninstall Code Notes, you want to also delete all notes?
And the day I reinstall a new version, I cannot retrieve my old notes?
Plus, what is the behaviour if someone upgrade its application by installing a new version? I hope it will not lose its notes.

**Comment by kodaman2** [comment]
> Thanks @kodaman2.
> So, when I uninstall Code Notes, you want to also delete all notes?
> And the day I reinstall a new version, I cannot retrieve my old notes?
> Plus, what is the behaviour if someone upgrade its application by installing a new version? I hope it will not lose its notes.

Correct, the uninstall electron configuration will delete all data left in roaming folder in windows, this includes code-notes data, and Code Notes also makes an installer folder in the roaming folder. If you install a new version it will not overwrite if notes exists so it will keep old notes as they are. So this is what you would expect from an installer, problem is local notes are in there, but if they are corrupt data then it will prevent user from launching application. I guess that shouldn't be a problem anymore since we are preventing erroneous local notes with #123 

Are you thinking perhaps we should save local notes somehow with uninstall, or perhaps a popup to save data somewhere else?

We could also ignore this PR, and we can just manually deal with the data since is not that big deal. We could add paths in the help menu. What are your thoughts on this PR?

**Comment by lauthieb** [comment]
Okay, it's ok for me.
I just want to guarantee that if someone upgrade Code Notes by installing the new .exe file, it will not lose its note...
Are you sure?

**Comment by lauthieb** [comment]
I hope that a replacement is not triggered as a uninstallation...

**Comment by kodaman2** [comment]
@lauthieb No, I've actually tested uninstall and install it too, installing will not trigger an uninstall, only uninstall.exe. I will do some more testing, because I guess the only reason we want users to uninstall is due to corrupt user data. 

Perhaps we could add another menu item to backup/import notes as a secondary option.

I dunno if we can implement a popup with install/uninstall like some installers ask you if you want to import configurations during installation prompts.

**Comment by kodaman2** [comment]
Closing PR, on hindsight I don't think this might be a desired feature. If a windows user uninstalls without saving their local notes, they might go crazy lol. For now I think it might be best to leave data behind since notes might be important.

I tried configuring the uninstaller but there is no easy way to add a checkbox for saving data before uninstall. Custom installer is a path I'd rather not go for now.

**Pull request closed without merging**
