### PR TITLE
made the update-note modal re-sizable to be more user-friendly

### PR DESCRIPTION
**Pull request by anushabachu03**
Implemented one of the ideas in this issue https://github.com/lauthieb/code-notes/issues/13

Made the update-note modal re-sizable to give user option to re-size the update popup and get more space to edit existing note.

image

image

The implementation can be extended for other modals as needed

### CODE REVIEW

**Comment by anushabachu03** [comment]
Thank you for reviewing my PR. Sure, I will work on that!

**Comment by BlackMix** [comment]
this pr need fix, u need change all this.$parent.close() to this.$modal.hide('name etc')

**Comment by lauthieb** [comment]
Hi @lnrdnl, can you please fix these conflicts?
I cannot merge your PR for the moment. :-)

**Comment by lauthieb** [comment]
Hi @anushabachu03, can you please fix these conflicts?
I cannot merge your PR for the moment. :-)

**Comment by anushabachu03** [comment]
@lauthieb I have fixed the merge conflicts, other issues with modal closing and added the same behavior for « create-note-modal ». Please review it.

**Comment by lauthieb** [comment]
Thanks a lot @anushabachu03. Merged 💌

**Pull request merged**
