### PR TITLE
add support for i18n for EN and FR

### PR DESCRIPTION
**Pull request by Netoun**
This was not required but I added i18n support to allow the management of several languages (en, fr) and add buefy dropdown in navbar to change.

packages :  vue-i18n (^8.15.0)

### CODE REVIEW

**Comment by lauthieb** [comment]
Wow, thanks @Netoun for this great PR.
I will check it as soon as possible. Thanks!

**Comment by Netoun** [comment]
I don't think I translated everything because of lack of time

Moreover, i need a little refacto in value ok key translation. I can take the time this weekend to fix several translations

**Comment by lauthieb** [comment]
As you want @Netoun :)

**Comment by lauthieb** [comment]
@Netoun Can you please fix conflicts and update your branch with just your modifications?
Sorry for the inconvenience it was mandatory to force push master after several tries to fix this important bug #110

Here you can download the new version 1.2.3 : https://github.com/lauthieb/code-notes/releases/tag/1.2.3

Thanks a lot in advance for this.

**Comment by lauthieb** [comment]
Hi @Netoun, happy new year 🎉
What about the conflict resolution and this issue?
Do you want to continue this Pull Request?
Thanks a in advance. Have a great day :)

**Comment by lauthieb** [comment]
Closed for the moment since there is no activity.
Feel free to reopen :)

**Pull request closed without merging**
