### PR TITLE
Feature/editor full screen mode

### LINKED ISSUE #69: Very small edit window for text
Hello everyone looks like the very cool program but only one features what I think it necessary provide, it needs to make a window where you create a note bigger, for me, it very hard writes some information it in this so small window, if you can make this window bigger it will a greate!

Best regards,
Andrew

### PR DESCRIPTION
**Pull request by probil**
Fixes #69
- Adds fullscreen mode during edition and creation of code snippet
- Increases font size in editor a bit

Screenshot from 2019-10-13 15-14-45
Screenshot from 2019-10-13 15-15-02

### CODE REVIEW

**Comment by lauthieb** [comment]
Hi @probil, thanks a lot for this PR.
I’m on vacation sorry but I will review and test your work ASAP.
Thank you

**Comment by probil** [comment]
Hi @lauthieb Thanks for response
Take your time :) I'll try to fix other things in the meanwhile

**Comment by lauthieb** [comment]
Nice @probil! Thanks a lot for your work on Code Notes.
But on MacOS, I've got this (the editor appears on topbar) :
Capture d’écran 2019-10-18 à 00 24 45

**Comment by probil** [comment]
@lauthieb I'm not an expert in electron but I think there should be some kind of configuration to enable on Mac (similar to windows & linux)

Any ideas?

**Comment by lauthieb** [comment]
@probil nope sorry, maybe you should get some advices from the community of our contributors.
Thanks a lot again for this work and sorry for the delay, I haven't so much time for Code Notes now... :(

**Comment by lauthieb** [comment]
@probil Can you please fix conflicts and update your branch with just your modifications?
Sorry for the inconvenience it was mandatory to force push master after several tries to fix this important bug #110

Here you can download the new version 1.2.3 : https://github.com/lauthieb/code-notes/releases/tag/1.2.3

Thanks a lot in advance for this.

**Comment by lauthieb** [comment]
Hi @probil, happy new year 🎉
What about the conflict resolution and this issue?
Do you want to continue this Pull Request?
Thanks a in advance. Have a great day :)

**Comment by probil** [comment]
@lauthieb Happy New Year!
yeah, I will rebase it on latest master and resolve conflicts

**Comment by probil** [comment]
@lauthieb done

**Comment by lauthieb** [comment]
Hi @probil,
I've just marked your Pull Request as closed because it has not had recent activity. 
It will be closed if no further activity occurs. 
Feel free to reopen it if you have time to contribute and fix conflicts... I haven't got any time to help you on this sorry...
Thanks again for your contributions.

**Pull request closed without merging**
